package com.practicaWipay.client_service.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;

import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class MainTable {
    @DynamoDBHashKey(attributeName = "PK")
    @JsonProperty("PK")
    @DynamoDBAutoGeneratedKey
    private String PK;

    @DynamoDBRangeKey(attributeName = "SK")
    @JsonProperty("SK")
    private String SK;
    @DynamoDBAttribute(attributeName = "id")
    @Id
    private String id;
    @DynamoDBAttribute(attributeName = "status")
    private String status;
    @DynamoDBAttribute(attributeName = "gIndex2Pk")
    @JsonProperty("gIndex2Pk")
    private String gIndex2Pk;
    @DynamoDBAutoGeneratedTimestamp
    private String createdDate;


}
